### ISSUE TITLE
Проект не стартует

### ISSUE THREAD

**Issue by khodyrevyurii** [dyp2000/docker-redis-cluster#1]
Шаги
1. Запускаем проект
`make start`
стартует без ошибок
![image](https://user-images.githubusercontent.com/52669813/94921477-d39eae80-04d1-11eb-98c3-fbb1a0638864.png)
2. В браузере по адресу http://localhost:8080/ видим оишбку
![image](https://user-images.githubusercontent.com/52669813/94921556-fc26a880-04d1-11eb-90f1-0420b2a42af9.png)

Вывод docker-compose logs
`Attaching to redis-stat, redis-slave-3, redis-slave-1, redis-slave-2, redis-master-2, redis-master-3, redis-master-1
redis-master-3    | 1:C 02 Oct 2020 12:06:49.509 # Can't chdir to '/var/redis/master-3': No such file or directory
redis-master-3    | 1:C 02 Oct 2020 12:06:50.940 # Can't chdir to '/var/redis/master-3': No such file or directory
redis-master-3    | 1:C 02 Oct 2020 12:06:52.870 # Can't chdir to '/var/redis/master-3': No such file or directory
redis-master-3    | 1:C 02 Oct 2020 12:06:54.568 # Can't chdir to '/var/redis/master-3': No such file or directory
redis-master-3    | 1:C 02 Oct 2020 12:06:56.643 # Can't chdir to '/var/redis/master-3': No such file or directory
redis-master-3    | 1:C 02 Oct 2020 12:06:58.991 # Can't chdir to '/var/redis/master-3': No such file or directory
redis-master-3    | 1:C 02 Oct 2020 12:07:02.901 # Can't chdir to '/var/redis/master-3': No such file or directory
redis-master-3    | 1:C 02 Oct 2020 12:07:10.065 # Can't chdir to '/var/redis/master-3': No such file or directory
redis-master-3    | 1:C 02 Oct 2020 12:07:23.491 # Can't chdir to '/var/redis/master-3': No such file or directory
redis-master-3    | 1:C 02 Oct 2020 12:07:49.747 # Can't chdir to '/var/redis/master-3': No such file or directory
redis-master-3    | 1:C 02 Oct 2020 12:08:41.509 # Can't chdir to '/var/redis/master-3': No such file or directory
redis-master-3    | 1:C 02 Oct 2020 12:09:42.178 # Can't chdir to '/var/redis/master-3': No such file or directory
redis-slave-1     | 1:C 02 Oct 2020 12:06:50.636 # Can't chdir to '/var/redis/slave-1': No such file or directory
redis-slave-1     | 1:C 02 Oct 2020 12:06:52.035 # Can't chdir to '/var/redis/slave-1': No such file or directory
redis-slave-1     | 1:C 02 Oct 2020 12:06:53.655 # Can't chdir to '/var/redis/slave-1': No such file or directory
redis-slave-1     | 1:C 02 Oct 2020 12:06:54.891 # Can't chdir to '/var/redis/slave-1': No such file or directory
redis-slave-1     | 1:C 02 Oct 2020 12:06:56.817 # Can't chdir to '/var/redis/slave-1': No such file or directory
redis-slave-1     | 1:C 02 Oct 2020 12:06:59.095 # Can't chdir to '/var/redis/slave-1': No such file or directory
redis-slave-1     | 1:C 02 Oct 2020 12:07:03.023 # Can't chdir to '/var/redis/slave-1': No such file or directory
redis-slave-1     | 1:C 02 Oct 2020 12:07:10.181 # Can't chdir to '/var/redis/slave-1': No such file or directory
redis-slave-1     | 1:C 02 Oct 2020 12:07:23.786 # Can't chdir to '/var/redis/slave-1': No such file or directory
redis-slave-1     | 1:C 02 Oct 2020 12:07:50.038 # Can't chdir to '/var/redis/slave-1': No such file or directory
redis-slave-1     | 1:C 02 Oct 2020 12:08:41.890 # Can't chdir to '/var/redis/slave-1': No such file or directory
redis-slave-1     | 1:C 02 Oct 2020 12:09:42.427 # Can't chdir to '/var/redis/slave-1': No such file or directory
redis-master-2    | 1:C 02 Oct 2020 12:06:49.265 # Can't chdir to '/var/redis/master-2': No such file or directory
redis-master-2    | 1:C 02 Oct 2020 12:06:50.379 # Can't chdir to '/var/redis/master-2': No such file or directory
redis-master-2    | 1:C 02 Oct 2020 12:06:51.924 # Can't chdir to '/var/redis/master-2': No such file or directory
redis-master-2    | 1:C 02 Oct 2020 12:06:53.649 # Can't chdir to '/var/redis/master-2': No such file or directory
redis-master-2    | 1:C 02 Oct 2020 12:06:55.356 # Can't chdir to '/var/redis/master-2': No such file or directory
redis-master-2    | 1:C 02 Oct 2020 12:06:57.788 # Can't chdir to '/var/redis/master-2': No such file or directory
redis-master-2    | 1:C 02 Oct 2020 12:07:01.585 # Can't chdir to '/var/redis/master-2': No such file or directory
redis-master-2    | 1:C 02 Oct 2020 12:07:08.579 # Can't chdir to '/var/redis/master-2': No such file or directory
redis-master-2    | 1:C 02 Oct 2020 12:07:21.985 # Can't chdir to '/var/redis/master-2': No such file or directory
redis-master-2    | 1:C 02 Oct 2020 12:07:48.166 # Can't chdir to '/var/redis/master-2': No such file or directory
redis-master-2    | 1:C 02 Oct 2020 12:08:39.968 # Can't chdir to '/var/redis/master-2': No such file or directory
redis-master-2    | 1:C 02 Oct 2020 12:09:40.558 # Can't chdir to '/var/redis/master-2': No such file or directory
redis-master-1    | 1:C 02 Oct 2020 12:06:49.508 # Can't chdir to '/var/redis/master-1': No such file or directory
redis-master-1    | 1:C 02 Oct 2020 12:06:51.048 # Can't chdir to '/var/redis/master-1': No such file or directory
redis-master-1    | 1:C 02 Oct 2020 12:06:52.849 # Can't chdir to '/var/redis/master-1': No such file or directory
redis-master-1    | 1:C 02 Oct 2020 12:06:54.530 # Can't chdir to '/var/redis/master-1': No such file or directory
redis-master-1    | 1:C 02 Oct 2020 12:06:56.935 # Can't chdir to '/var/redis/master-1': No such file or directory
redis-master-1    | 1:C 02 Oct 2020 12:06:59.224 # Can't chdir to '/var/redis/master-1': No such file or directory
redis-master-1    | 1:C 02 Oct 2020 12:07:03.176 # Can't chdir to '/var/redis/master-1': No such file or directory
redis-master-1    | 1:C 02 Oct 2020 12:07:10.391 # Can't chdir to '/var/redis/master-1': No such file or directory
redis-master-1    | 1:C 02 Oct 2020 12:07:24.513 # Can't chdir to '/var/redis/master-1': No such file or directory
redis-master-1    | 1:C 02 Oct 2020 12:07:50.743 # Can't chdir to '/var/redis/master-1': No such file or directory
redis-master-1    | 1:C 02 Oct 2020 12:08:42.600 # Can't chdir to '/var/redis/master-1': No such file or directory
redis-master-1    | 1:C 02 Oct 2020 12:09:43.140 # Can't chdir to '/var/redis/master-1': No such file or directory
redis-slave-3     | 1:C 02 Oct 2020 12:06:50.950 # Can't chdir to '/var/redis/slave-3': No such file or directory
redis-slave-3     | 1:C 02 Oct 2020 12:06:52.853 # Can't chdir to '/var/redis/slave-3': No such file or directory
redis-slave-3     | 1:C 02 Oct 2020 12:06:54.276 # Can't chdir to '/var/redis/slave-3': No such file or directory
redis-slave-3     | 1:C 02 Oct 2020 12:06:56.474 # Can't chdir to '/var/redis/slave-3': No such file or directory
redis-slave-3     | 1:C 02 Oct 2020 12:06:57.835 # Can't chdir to '/var/redis/slave-3': No such file or directory
redis-slave-3     | 1:C 02 Oct 2020 12:06:59.948 # Can't chdir to '/var/redis/slave-3': No such file or directory
redis-slave-3     | 1:C 02 Oct 2020 12:07:04.099 # Can't chdir to '/var/redis/slave-3': No such file or directory
redis-slave-3     | 1:C 02 Oct 2020 12:07:11.278 # Can't chdir to '/var/redis/slave-3': No such file or directory
redis-slave-3     | 1:C 02 Oct 2020 12:07:25.017 # Can't chdir to '/var/redis/slave-3': No such file or directory
redis-slave-3     | 1:C 02 Oct 2020 12:07:51.309 # Can't chdir to '/var/redis/slave-3': No such file or directory
redis-slave-3     | 1:C 02 Oct 2020 12:08:43.147 # Can't chdir to '/var/redis/slave-3': No such file or directory
redis-stat        | /usr/local/bundle/gems/sinatra-1.3.6/lib/sinatra/base.rb:1070: warning: constant ::Fixnum is deprecated
redis-stat        | /usr/local/bundle/gems/sinatra-1.3.6/lib/sinatra/base.rb:1070: warning: constant ::Fixnum is deprecated
redis-stat        | /usr/local/bundle/gems/sinatra-1.3.6/lib/sinatra/base.rb:1070: warning: constant ::Fixnum is deprecated
redis-stat        | /usr/local/bundle/gems/sinatra-1.3.6/lib/sinatra/base.rb:1070: warning: constant ::Fixnum is deprecated
redis-stat        | /usr/local/bundle/gems/sinatra-1.3.6/lib/sinatra/base.rb:1070: warning: constant ::Fixnum is deprecated
redis-stat        | /usr/local/bundle/gems/si-0.1.4/lib/si/patch.rb:5: warning: constant ::Fixnum is deprecated
redis-stat        | /usr/local/bundle/gems/si-0.1.4/lib/si/patch.rb:9: warning: constant ::Bignum is deprecated
redis-stat        | /usr/local/bundle/gems/option_initializer-1.5.1/lib/option_initializer.rb:154: warning: constant ::Fixnum is deprecated
redis-stat        | /usr/local/bundle/gems/option_initializer-1.5.1/lib/option_initializer.rb:198: warning: constant ::Fixnum is deprecated
redis-stat        | /usr/local/bundle/gems/redis-3.0.7/lib/redis/client.rb:386: warning: constant ::Fixnum is deprecated
redis-stat        | tput: No value for $TERM and no -T specified
redis-stat        | tput: No value for $TERM and no -T specified
redis-stat        | [2020/10/02 12:06:54@10.5.0.10] Timed out connecting to Redis on 10.5.0.10:6379
redis-stat        | [2020/10/02 12:06:54@10.5.0.11] Timed out connecting to Redis on 10.5.0.11:6379
redis-stat        | [2020/10/02 12:06:54@10.5.0.12] Error connecting to Redis on 10.5.0.12:6379 (ECONNREFUSED)
redis-stat        | [2020/10/02 12:06:54@10.5.0.13] Timed out connecting to Redis on 10.5.0.13:6379
redis-stat        | [2020/10/02 12:06:54@10.5.0.14] Timed out connecting to Redis on 10.5.0.14:6379
redis-stat        | [2020/10/02 12:06:54@10.5.0.15] Error connecting to Redis on 10.5.0.15:6379 (ECONNREFUSED)
redis-stat exited with code 0
redis-slave-2     | 1:C 02 Oct 2020 12:06:50.296 # Can't chdir to '/var/redis/slave-2': No such file or directory
redis-slave-2     | 1:C 02 Oct 2020 12:06:51.859 # Can't chdir to '/var/redis/slave-2': No such file or directory
redis-slave-2     | 1:C 02 Oct 2020 12:06:53.271 # Can't chdir to '/var/redis/slave-2': No such file or directory
redis-slave-2     | 1:C 02 Oct 2020 12:06:54.669 # Can't chdir to '/var/redis/slave-2': No such file or directory
redis-slave-2     | 1:C 02 Oct 2020 12:06:56.863 # Can't chdir to '/var/redis/slave-2': No such file or directory
redis-slave-2     | 1:C 02 Oct 2020 12:06:59.152 # Can't chdir to '/var/redis/slave-2': No such file or directory
redis-slave-2     | 1:C 02 Oct 2020 12:07:03.068 # Can't chdir to '/var/redis/slave-2': No such file or directory
redis-slave-2     | 1:C 02 Oct 2020 12:07:10.290 # Can't chdir to '/var/redis/slave-2': No such file or directory
redis-slave-2     | 1:C 02 Oct 2020 12:07:24.298 # Can't chdir to '/var/redis/slave-2': No such file or directory
redis-slave-2     | 1:C 02 Oct 2020 12:07:50.539 # Can't chdir to '/var/redis/slave-2': No such file or directory
redis-slave-2     | 1:C 02 Oct 2020 12:08:42.384 # Can't chdir to '/var/redis/slave-2': No such file or directory
redis-slave-2     | 1:C 02 Oct 2020 12:09:42.993 # Can't chdir to '/var/redis/slave-2': No such file or directory
redis-slave-3 exited with code 1
`

**Comment by dyp2000** [comment]
Да. Забыл каталоги добавить в репозиторий.
Добавил.
И пока нет балансировки и точки входа с хоста.

**Comment by dyp2000** [comment]
Проблема решена.
